# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-guestbook
spec:
  replicas: 2  # We want 2 copies for high availability
  selector:
    matchLabels:
      app: custom-guestbook
  template:
    metadata:
      labels:
        app: custom-guestbook
    spec:
      containers:
      - name: guestbook-ui
        image: nginx:1.25.1
        ports:
        - containerPort: 80
